fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    concat: https://github.com/ripienaar/puppet-concat.git
    logrotate: https://github.com/UCSD-ANF/puppet-logrotate.git
  symlinks:
    apache_anf: "#{source_dir}"
